import Head from 'next/head';

import Banner from '@/components/banner/Banner';

import styles from '@/styles/Home.module.scss';

export default function Home() {
	function handleBtnClick() {
		console.log('banner button');
	}
	return (
		<>
			<Head>
				<title>Kahawa Epicurean</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.home}>
				<Banner
					btnText="view stores nearby"
					btnHandler={handleBtnClick}
				/>
			</main>
		</>
	);
}
